logging:
  level:
    root: INFO
server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://sublearn-competition-db:5432/competitiondb
    username: postgres
    password: passw0rd
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:liquibase/liquibase-changelog.xml
    liquibase-schema: liquibase
    enabled: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 45000
          max-attempts: 10

rabbitmq:
    queue: trial-word-result
project:
  version: '@project.version@'