/*
 * This file is generated by jOOQ.
 */
package ru.zagamaza.competition.infra.dao.jooq.schema.tables.records;


import java.time.OffsetDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import ru.zagamaza.competition.infra.dao.jooq.schema.tables.League;


/**
 * Таблица лиги, опыт всех пользователей
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LeagueRecord extends UpdatableRecordImpl<LeagueRecord> implements Record5<Integer, Integer, Integer, Integer, OffsetDateTime> {

    private static final long serialVersionUID = -1311571830;

    /**
     * Setter for <code>public.league.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.league.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.league.user_id</code>. идентификатор пользователя
     */
    public void setUserId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.league.user_id</code>. идентификатор пользователя
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.league.experience</code>. Количество опыта
     */
    public void setExperience(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.league.experience</code>. Количество опыта
     */
    public Integer getExperience() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.league.level_id</code>. идентификатор уровня лиги
     */
    public void setLevelId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.league.level_id</code>. идентификатор уровня лиги
     */
    public Integer getLevelId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.league.created</code>.
     */
    public void setCreated(OffsetDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.league.created</code>.
     */
    public OffsetDateTime getCreated() {
        return (OffsetDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Integer, Integer, OffsetDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Integer, Integer, OffsetDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return League.LEAGUE_ENTITY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return League.LEAGUE_ENTITY.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return League.LEAGUE_ENTITY.EXPERIENCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return League.LEAGUE_ENTITY.LEVEL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<OffsetDateTime> field5() {
        return League.LEAGUE_ENTITY.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getExperience();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getLevelId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime component5() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getExperience();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getLevelId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime value5() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LeagueRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LeagueRecord value2(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LeagueRecord value3(Integer value) {
        setExperience(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LeagueRecord value4(Integer value) {
        setLevelId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LeagueRecord value5(OffsetDateTime value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LeagueRecord values(Integer value1, Integer value2, Integer value3, Integer value4, OffsetDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LeagueRecord
     */
    public LeagueRecord() {
        super(League.LEAGUE_ENTITY);
    }

    /**
     * Create a detached, initialised LeagueRecord
     */
    public LeagueRecord(Integer id, Integer userId, Integer experience, Integer levelId, OffsetDateTime created) {
        super(League.LEAGUE_ENTITY);

        set(0, id);
        set(1, userId);
        set(2, experience);
        set(3, levelId);
        set(4, created);
    }
}
