/*
 * This file is generated by jOOQ.
 */
package ru.zagamaza.competition.infra.dao.jooq.schema;


import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;

import ru.zagamaza.competition.infra.dao.jooq.schema.tables.League;
import ru.zagamaza.competition.infra.dao.jooq.schema.tables.LeagueLevel;
import ru.zagamaza.competition.infra.dao.jooq.schema.tables.User;
import ru.zagamaza.competition.infra.dao.jooq.schema.tables.UserFriend;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index LEAGUE_LEVEL_ID_IX = Indexes0.LEAGUE_LEVEL_ID_IX;
    public static final Index LEAGUE_PKEY = Indexes0.LEAGUE_PKEY;
    public static final Index LEAGUE_USER_ID_IX = Indexes0.LEAGUE_USER_ID_IX;
    public static final Index LEAGUE_LEVEL_PKEY = Indexes0.LEAGUE_LEVEL_PKEY;
    public static final Index USER_LEVEL_ID_IX = Indexes0.USER_LEVEL_ID_IX;
    public static final Index USER_PKEY = Indexes0.USER_PKEY;
    public static final Index USER_FRIEND_PKEY = Indexes0.USER_FRIEND_PKEY;
    public static final Index USER_FRIEND_USER_FRIEND_ID_IX = Indexes0.USER_FRIEND_USER_FRIEND_ID_IX;
    public static final Index USER_FRIEND_USER_ID_IX = Indexes0.USER_FRIEND_USER_ID_IX;
    public static final Index USER_FRIEND_USER_ID_USER_FRIEND_ID_AK = Indexes0.USER_FRIEND_USER_ID_USER_FRIEND_ID_AK;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index LEAGUE_LEVEL_ID_IX = Internal.createIndex("league_level_id_ix", League.LEAGUE_ENTITY, new OrderField[] { League.LEAGUE_ENTITY.LEVEL_ID }, false);
        public static Index LEAGUE_PKEY = Internal.createIndex("league_pkey", League.LEAGUE_ENTITY, new OrderField[] { League.LEAGUE_ENTITY.ID }, true);
        public static Index LEAGUE_USER_ID_IX = Internal.createIndex("league_user_id_ix", League.LEAGUE_ENTITY, new OrderField[] { League.LEAGUE_ENTITY.USER_ID }, false);
        public static Index LEAGUE_LEVEL_PKEY = Internal.createIndex("league_level_pkey", LeagueLevel.LEAGUE_LEVEL_ENTITY, new OrderField[] { LeagueLevel.LEAGUE_LEVEL_ENTITY.ID }, true);
        public static Index USER_LEVEL_ID_IX = Internal.createIndex("user_level_id_ix", User.USER_ENTITY, new OrderField[] { User.USER_ENTITY.LEVEL_ID }, false);
        public static Index USER_PKEY = Internal.createIndex("user_pkey", User.USER_ENTITY, new OrderField[] { User.USER_ENTITY.ID }, true);
        public static Index USER_FRIEND_PKEY = Internal.createIndex("user_friend_pkey", UserFriend.USER_FRIEND_ENTITY, new OrderField[] { UserFriend.USER_FRIEND_ENTITY.ID }, true);
        public static Index USER_FRIEND_USER_FRIEND_ID_IX = Internal.createIndex("user_friend_user_friend_id_ix", UserFriend.USER_FRIEND_ENTITY, new OrderField[] { UserFriend.USER_FRIEND_ENTITY.USER_FRIEND_ID }, false);
        public static Index USER_FRIEND_USER_ID_IX = Internal.createIndex("user_friend_user_id_ix", UserFriend.USER_FRIEND_ENTITY, new OrderField[] { UserFriend.USER_FRIEND_ENTITY.USER_ID }, false);
        public static Index USER_FRIEND_USER_ID_USER_FRIEND_ID_AK = Internal.createIndex("user_friend_user_id_user_friend_id_ak", UserFriend.USER_FRIEND_ENTITY, new OrderField[] { UserFriend.USER_FRIEND_ENTITY.USER_ID, UserFriend.USER_FRIEND_ENTITY.USER_FRIEND_ID }, true);
    }
}
