/*
 * This file is generated by jOOQ.
 */
package ru.zagamaza.competition.infra.dao.jooq.schema;


import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;

import ru.zagamaza.competition.infra.dao.jooq.schema.tables.League;
import ru.zagamaza.competition.infra.dao.jooq.schema.tables.LeagueLevel;
import ru.zagamaza.competition.infra.dao.jooq.schema.tables.User;
import ru.zagamaza.competition.infra.dao.jooq.schema.tables.UserFriend;
import ru.zagamaza.competition.infra.dao.jooq.schema.tables.records.LeagueLevelRecord;
import ru.zagamaza.competition.infra.dao.jooq.schema.tables.records.LeagueRecord;
import ru.zagamaza.competition.infra.dao.jooq.schema.tables.records.UserFriendRecord;
import ru.zagamaza.competition.infra.dao.jooq.schema.tables.records.UserRecord;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<LeagueRecord, Integer> IDENTITY_LEAGUE_ENTITY = Identities0.IDENTITY_LEAGUE_ENTITY;
    public static final Identity<LeagueLevelRecord, Integer> IDENTITY_LEAGUE_LEVEL_ENTITY = Identities0.IDENTITY_LEAGUE_LEVEL_ENTITY;
    public static final Identity<UserFriendRecord, Integer> IDENTITY_USER_FRIEND_ENTITY = Identities0.IDENTITY_USER_FRIEND_ENTITY;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<LeagueRecord> LEAGUE_PKEY = UniqueKeys0.LEAGUE_PKEY;
    public static final UniqueKey<LeagueLevelRecord> LEAGUE_LEVEL_PKEY = UniqueKeys0.LEAGUE_LEVEL_PKEY;
    public static final UniqueKey<UserRecord> USER_PKEY = UniqueKeys0.USER_PKEY;
    public static final UniqueKey<UserFriendRecord> USER_FRIEND_PKEY = UniqueKeys0.USER_FRIEND_PKEY;
    public static final UniqueKey<UserFriendRecord> USER_FRIEND_USER_ID_USER_FRIEND_ID_AK = UniqueKeys0.USER_FRIEND_USER_ID_USER_FRIEND_ID_AK;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<LeagueRecord, UserRecord> LEAGUE__LEAGUE_USER_ID_FK = ForeignKeys0.LEAGUE__LEAGUE_USER_ID_FK;
    public static final ForeignKey<LeagueRecord, LeagueLevelRecord> LEAGUE__USER_LEVEL_ID_FK = ForeignKeys0.LEAGUE__USER_LEVEL_ID_FK;
    public static final ForeignKey<UserRecord, LeagueLevelRecord> USER__USER_LEVEL_ID_FK = ForeignKeys0.USER__USER_LEVEL_ID_FK;
    public static final ForeignKey<UserFriendRecord, UserRecord> USER_FRIEND__USER_FRIEND_USER_ID_FK = ForeignKeys0.USER_FRIEND__USER_FRIEND_USER_ID_FK;
    public static final ForeignKey<UserFriendRecord, UserRecord> USER_FRIEND__USER_USER_ID_FK = ForeignKeys0.USER_FRIEND__USER_USER_ID_FK;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<LeagueRecord, Integer> IDENTITY_LEAGUE_ENTITY = Internal.createIdentity(League.LEAGUE_ENTITY, League.LEAGUE_ENTITY.ID);
        public static Identity<LeagueLevelRecord, Integer> IDENTITY_LEAGUE_LEVEL_ENTITY = Internal.createIdentity(LeagueLevel.LEAGUE_LEVEL_ENTITY, LeagueLevel.LEAGUE_LEVEL_ENTITY.ID);
        public static Identity<UserFriendRecord, Integer> IDENTITY_USER_FRIEND_ENTITY = Internal.createIdentity(UserFriend.USER_FRIEND_ENTITY, UserFriend.USER_FRIEND_ENTITY.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<LeagueRecord> LEAGUE_PKEY = Internal.createUniqueKey(League.LEAGUE_ENTITY, "league_pkey", League.LEAGUE_ENTITY.ID);
        public static final UniqueKey<LeagueLevelRecord> LEAGUE_LEVEL_PKEY = Internal.createUniqueKey(LeagueLevel.LEAGUE_LEVEL_ENTITY, "league_level_pkey", LeagueLevel.LEAGUE_LEVEL_ENTITY.ID);
        public static final UniqueKey<UserRecord> USER_PKEY = Internal.createUniqueKey(User.USER_ENTITY, "user_pkey", User.USER_ENTITY.ID);
        public static final UniqueKey<UserFriendRecord> USER_FRIEND_PKEY = Internal.createUniqueKey(UserFriend.USER_FRIEND_ENTITY, "user_friend_pkey", UserFriend.USER_FRIEND_ENTITY.ID);
        public static final UniqueKey<UserFriendRecord> USER_FRIEND_USER_ID_USER_FRIEND_ID_AK = Internal.createUniqueKey(UserFriend.USER_FRIEND_ENTITY, "user_friend_user_id_user_friend_id_ak", UserFriend.USER_FRIEND_ENTITY.USER_ID, UserFriend.USER_FRIEND_ENTITY.USER_FRIEND_ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<LeagueRecord, UserRecord> LEAGUE__LEAGUE_USER_ID_FK = Internal.createForeignKey(ru.zagamaza.competition.infra.dao.jooq.schema.Keys.USER_PKEY, League.LEAGUE_ENTITY, "league__league_user_id_fk", League.LEAGUE_ENTITY.USER_ID);
        public static final ForeignKey<LeagueRecord, LeagueLevelRecord> LEAGUE__USER_LEVEL_ID_FK = Internal.createForeignKey(ru.zagamaza.competition.infra.dao.jooq.schema.Keys.LEAGUE_LEVEL_PKEY, League.LEAGUE_ENTITY, "league__user_level_id_fk", League.LEAGUE_ENTITY.LEVEL_ID);
        public static final ForeignKey<UserRecord, LeagueLevelRecord> USER__USER_LEVEL_ID_FK = Internal.createForeignKey(ru.zagamaza.competition.infra.dao.jooq.schema.Keys.LEAGUE_LEVEL_PKEY, User.USER_ENTITY, "user__user_level_id_fk", User.USER_ENTITY.LEVEL_ID);
        public static final ForeignKey<UserFriendRecord, UserRecord> USER_FRIEND__USER_FRIEND_USER_ID_FK = Internal.createForeignKey(ru.zagamaza.competition.infra.dao.jooq.schema.Keys.USER_PKEY, UserFriend.USER_FRIEND_ENTITY, "user_friend__user_friend_user_id_fk", UserFriend.USER_FRIEND_ENTITY.USER_ID);
        public static final ForeignKey<UserFriendRecord, UserRecord> USER_FRIEND__USER_USER_ID_FK = Internal.createForeignKey(ru.zagamaza.competition.infra.dao.jooq.schema.Keys.USER_PKEY, UserFriend.USER_FRIEND_ENTITY, "user_friend__user_user_id_fk", UserFriend.USER_FRIEND_ENTITY.USER_FRIEND_ID);
    }
}
