/*
 * This file is generated by jOOQ.
 */
package ru.zagamaza.competition.infra.dao.jooq.schema;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import ru.zagamaza.competition.infra.dao.jooq.schema.tables.League;
import ru.zagamaza.competition.infra.dao.jooq.schema.tables.LeagueLevel;
import ru.zagamaza.competition.infra.dao.jooq.schema.tables.User;
import ru.zagamaza.competition.infra.dao.jooq.schema.tables.UserFriend;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -690606862;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * Таблица лиги, опыт всех пользователей
     */
    public final League LEAGUE_ENTITY = ru.zagamaza.competition.infra.dao.jooq.schema.tables.League.LEAGUE_ENTITY;

    /**
     * Таблица уроыней лиг
     */
    public final LeagueLevel LEAGUE_LEVEL_ENTITY = ru.zagamaza.competition.infra.dao.jooq.schema.tables.LeagueLevel.LEAGUE_LEVEL_ENTITY;

    /**
     * Таблица пользователей и его опыта
     */
    public final User USER_ENTITY = ru.zagamaza.competition.infra.dao.jooq.schema.tables.User.USER_ENTITY;

    /**
     * Таблица связи друзей
     */
    public final UserFriend USER_FRIEND_ENTITY = ru.zagamaza.competition.infra.dao.jooq.schema.tables.UserFriend.USER_FRIEND_ENTITY;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.LEAGUE_ID_SEQ,
            Sequences.LEAGUE_LEVEL_ID_SEQ,
            Sequences.USER_FRIEND_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            League.LEAGUE_ENTITY,
            LeagueLevel.LEAGUE_LEVEL_ENTITY,
            User.USER_ENTITY,
            UserFriend.USER_FRIEND_ENTITY);
    }
}
