/*
 * This file is generated by jOOQ.
 */
package ru.zagamaza.competition.infra.dao.jooq.schema;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.league_id_seq</code>
     */
    public static final Sequence<Integer> LEAGUE_ID_SEQ = new SequenceImpl<Integer>("league_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.league_level_id_seq</code>
     */
    public static final Sequence<Integer> LEAGUE_LEVEL_ID_SEQ = new SequenceImpl<Integer>("league_level_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.user_friend_id_seq</code>
     */
    public static final Sequence<Integer> USER_FRIEND_ID_SEQ = new SequenceImpl<Integer>("user_friend_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));
}
