/*
 * This file is generated by jOOQ.
 */
package ru.zagamaza.competition.infra.dao.jooq.schema.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;

import javax.annotation.Generated;

import ru.zagamaza.competition.infra.dao.entity.Entity;


/**
 * Таблица лиги, опыт всех пользователей
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LeagueEntity implements Entity, Serializable {

    private static final long serialVersionUID = 1454792963;

    private Integer        id;
    private Integer        userId;
    private Integer        experience;
    private Integer        levelId;
    private OffsetDateTime created;

    public LeagueEntity() {}

    public LeagueEntity(LeagueEntity value) {
        this.id = value.id;
        this.userId = value.userId;
        this.experience = value.experience;
        this.levelId = value.levelId;
        this.created = value.created;
    }

    public LeagueEntity(
        Integer        id,
        Integer        userId,
        Integer        experience,
        Integer        levelId,
        OffsetDateTime created
    ) {
        this.id = id;
        this.userId = userId;
        this.experience = experience;
        this.levelId = levelId;
        this.created = created;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Integer getExperience() {
        return this.experience;
    }

    public void setExperience(Integer experience) {
        this.experience = experience;
    }

    public Integer getLevelId() {
        return this.levelId;
    }

    public void setLevelId(Integer levelId) {
        this.levelId = levelId;
    }

    public OffsetDateTime getCreated() {
        return this.created;
    }

    public void setCreated(OffsetDateTime created) {
        this.created = created;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final LeagueEntity other = (LeagueEntity) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!userId.equals(other.userId))
            return false;
        if (experience == null) {
            if (other.experience != null)
                return false;
        }
        else if (!experience.equals(other.experience))
            return false;
        if (levelId == null) {
            if (other.levelId != null)
                return false;
        }
        else if (!levelId.equals(other.levelId))
            return false;
        if (created == null) {
            if (other.created != null)
                return false;
        }
        else if (!created.equals(other.created))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.experience == null) ? 0 : this.experience.hashCode());
        result = prime * result + ((this.levelId == null) ? 0 : this.levelId.hashCode());
        result = prime * result + ((this.created == null) ? 0 : this.created.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("LeagueEntity (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(experience);
        sb.append(", ").append(levelId);
        sb.append(", ").append(created);

        sb.append(")");
        return sb.toString();
    }
}
