/*
 * This file is generated by jOOQ.
 */
package ru.zagamaza.competition.infra.dao.jooq.schema.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;

import javax.annotation.Generated;

import ru.zagamaza.competition.infra.dao.entity.Entity;


/**
 * Таблица версий уровня
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LeagueVersionEntity implements Entity, Serializable {

    private static final long serialVersionUID = -2119238340;

    private Long           id;
    private OffsetDateTime created;
    private Integer        version;

    public LeagueVersionEntity() {}

    public LeagueVersionEntity(LeagueVersionEntity value) {
        this.id = value.id;
        this.created = value.created;
        this.version = value.version;
    }

    public LeagueVersionEntity(
        Long           id,
        OffsetDateTime created,
        Integer        version
    ) {
        this.id = id;
        this.created = created;
        this.version = version;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public OffsetDateTime getCreated() {
        return this.created;
    }

    public void setCreated(OffsetDateTime created) {
        this.created = created;
    }

    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final LeagueVersionEntity other = (LeagueVersionEntity) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (created == null) {
            if (other.created != null)
                return false;
        }
        else if (!created.equals(other.created))
            return false;
        if (version == null) {
            if (other.version != null)
                return false;
        }
        else if (!version.equals(other.version))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.created == null) ? 0 : this.created.hashCode());
        result = prime * result + ((this.version == null) ? 0 : this.version.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("LeagueVersionEntity (");

        sb.append(id);
        sb.append(", ").append(created);
        sb.append(", ").append(version);

        sb.append(")");
        return sb.toString();
    }
}
