/*
 * This file is generated by jOOQ.
 */
package ru.zagamaza.competition.infra.dao.jooq.schema.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;

import javax.annotation.Generated;

import ru.zagamaza.competition.infra.dao.entity.Entity;


/**
 * Таблица пользователей и его опыта
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserEntity implements Entity, Serializable {

    private static final long serialVersionUID = -1858422022;

    private Integer        id;
    private OffsetDateTime created;
    private Integer        experience;
    private Integer        levelId;

    public UserEntity() {}

    public UserEntity(UserEntity value) {
        this.id = value.id;
        this.created = value.created;
        this.experience = value.experience;
        this.levelId = value.levelId;
    }

    public UserEntity(
        Integer        id,
        OffsetDateTime created,
        Integer        experience,
        Integer        levelId
    ) {
        this.id = id;
        this.created = created;
        this.experience = experience;
        this.levelId = levelId;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public OffsetDateTime getCreated() {
        return this.created;
    }

    public void setCreated(OffsetDateTime created) {
        this.created = created;
    }

    public Integer getExperience() {
        return this.experience;
    }

    public void setExperience(Integer experience) {
        this.experience = experience;
    }

    public Integer getLevelId() {
        return this.levelId;
    }

    public void setLevelId(Integer levelId) {
        this.levelId = levelId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final UserEntity other = (UserEntity) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (created == null) {
            if (other.created != null)
                return false;
        }
        else if (!created.equals(other.created))
            return false;
        if (experience == null) {
            if (other.experience != null)
                return false;
        }
        else if (!experience.equals(other.experience))
            return false;
        if (levelId == null) {
            if (other.levelId != null)
                return false;
        }
        else if (!levelId.equals(other.levelId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.created == null) ? 0 : this.created.hashCode());
        result = prime * result + ((this.experience == null) ? 0 : this.experience.hashCode());
        result = prime * result + ((this.levelId == null) ? 0 : this.levelId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserEntity (");

        sb.append(id);
        sb.append(", ").append(created);
        sb.append(", ").append(experience);
        sb.append(", ").append(levelId);

        sb.append(")");
        return sb.toString();
    }
}
